- .github/pull_request_template.md
- docs/contributor_guide/CODE_OF_CONDUCT.md
- docs/contributor_guide/CONTRIBUTING.md
Add your summary here - keep it brief, to the point, and in plain English. [For further
information about pull requests, check out the GDS
Way](https://gds-way.cloudapps.digital/standards/pull-requests.html).
This pull/merge request meets the following requirements:
necessary
Comments have been added below around the incomplete checks.
[agilemodeling]: http://agilemodeling.com/essays/documentLate.htm
[data-ethics-framework]: https://www.gov.uk/government/publications/data-ethics-framework
> Add requirements to pull request template following workshop

- .github/workflows/main.yaml
Add GitHub Actions workflow to check build and tests before merging to main branch
> Add workflow to build and test before merging to main

- .github/workflows/main.yaml
Add `on` statement so that build and test checks run on pull requests to main as well as direct merges
> Add on statement for pull requests to main

- src/flag_and_count_matched_pairs.py
- tests/test_flag_and_count_matched_pairs.py
Minor bug fixes in `flag_matched_pair_merge` and `flag_matched_pair_shift`
> Adding flag (f/b) to predictive column name

- .github/workflows/main.yaml
Adding in workflow to run pre-commit hooks before code can be merged into main
No changes have been made to main codebase 
> Add pre-commit hooks as test when merging

- docs/contributor_guide/CONTRIBUTING.md
Summarised today's team discussion on testing and functions
> added testing guide and function tips

- main.py
- mbs_results/data_cleaning.py
- mbs_results/validation_checks.py
> 376 validate merge

- config.json
- main.py
- mbs_results/data_cleaning.py
- tests/test_data_cleaning.py
Added function to enforce datatypes of the loaded data as per the schema.
Works by adapting the config file to include data types. 
Performs some checks on valid inputs and if same column has two conflicting data types.
Introduced method to temporarily remove columns while not having to delete data types.
> 374 convert types

- config.json
- main.py
- mbs_results/data_cleaning.py
- mbs_results/utils.py
- mbs_results/validation_checks.py
> Load and merge manual constructions into the main dataset

- mbs_results/ratio_of_means.py
If target is not question and strata not group the code will fail, updated the hard coded intermediate columns 
> Update column names

- mbs_results/validate_estimation.py
- mbs_results/validate_imputation.py
- tests/data/validate_estimation/validate_estimation.csv
- tests/test_validate_estimation.py
Check no missing values and totals for estimation
> Add validation for missing values and totals

- testing_main.py
> Change winsorisation group parameter

- mbs_results/growth_rate_output.py
- mbs_results/weighted_adj_val_time_series.py
> Change value and agg type

- mbs_results/outputs/get_additional_outputs.py
- tests/test_outputs/test_get_additional_outputs.py
> Feat get additional outputs function

- mbs_results/selective_editing_contributer_output.py
> Add function to merge dataframes on sic and return required columns

- testing_helpers.py
> 559 update froempees froempment

- Jenkinsfile
- requirements.txt
- setup.py
> Bump version

- testing_main.py
Removed quick fix to combine columns now this is being done in Ratio of Means function
Updated constrain column inputs to also reflect changes to main package
> 494 combined imputed adjusted outputs

- mbs_results/config.json
Forgotten calibration group in config, is essential for estimation mapping to cencus
> Add calibration group to config

- .github/workflows/CODEOWNERS
Created code owners doc. Codeowners picked from the repo settings 
Created code owners doc to be compliant with ONS digital requirements. Secret scanning and push protection have also been enabled in settings
CHECKLIST NOT APPROPRIATE AS ITS A GITHUB SPECIFIC CHANGE
> creating codeowners doc

- mbs_results/utilities/csw_to_spp_converter.py
CSW to SPP converter
Changed functionality to:
- create `status` column in contributors that includes nil markers and error markers
- take a list of periods so we can skip the back data period, which is handled elsewhere
- writes a json file that looks more like the SPP snapshots
> CSW to SPP converter

- mbs_results/utilities/csw_to_spp_converter.py
717 update csw spp converter
Updating the existing csw to spp data converter 
- Now correctly converts error and response types into the correct spp status. 
- load finalsel data to get needed idbr data 
- saves output into json file ready to use in main pipeline
Unit tests not updated: This is more of an integration test to show that the final output will be able to run in the main pipeline. Waiting for main integration tests to be developed before adding this test case
Have tested this myself and output of the convert function will run in the full pipeline and produce identical results to using spp data.
Please provide any …
> 717 update csw spp converter

- mbs_results/outputs/produce_additional_outputs.py
- mbs_results/outputs/selective_editing_contributer_output.py
Selective editing contributor filtering
Code added to now filter contributors which do not have the required questions for selective editing.
Only contributors with questions 40 or 49 will now be included in both selective editing files
> 734 se filtering

- mbs_results/utilities/csw_to_spp_converter.py
Adds a function to check for cases where type marker >=10 and adjusted value >0. If so then set the adjusted_value to 0, print a warning to the user, and create a log file containing the reference, period, and question number of these cases.
> Add validation function

- setup.cfg
> Bump version to 0.1.2

- mbs_results/outputs/back_data_wrapper.py
- mbs_results/outputs/produce_additional_outputs.py
> 723 backdata wrapper

- mbs_results/outputs/back_data_wrapper.py
- mbs_results/utilities/validation_checks.py
Added function to QA check selective editing outputs
code checks for duplicates, nulls/nans and mismatched references between contributors and questions files
> 777 qa function se outputs

- mbs_results/staging/back_data.py
> Add condition for start of period processing

- .github/workflows/main.yaml
- mbs_results/staging/data_cleaning.py
- mbs_results/staging/stage_dataframe.py
- mbs_results/utilities/utils.py
- mbs_results/utilities/validation_checks.py
- tests/data/test_main/input/test_snaphot.json
- tests/staging/test_data_cleaning.py
- This PR appends in the outputs the question codes which  were removed from the processing (question codes 11,12,146)
- Added a scenario with question code 146 for the test_main.py to test that functionality. 146 is removed from processing and added back to the final results
- When exporting filtered_out_questions forcing date format `%Y%M` e.g. `202001` for consistency  (raw date is converted to datetime for imputation and then converted back to int) 
- Used index=False when exporting csv 
- Also during exports added index=False 
Please provide any additional information or context that would help the reviewer understand the …
> 731 append filtered questions

- mbs_results/outputs/turnover_analysis.py
> Changing code to work without reference name column

- mbs_results/config.json
- mbs_results/imputation/impute.py
- mbs_results/staging/stage_dataframe.py
Update stage_dataframe to calculate monthly actual pounds and use this in imputation
This pull request implements [ASAP-800](https://jira.ons.gov.uk/browse/ASAP-800) by calling the convert_annual_thousands function in the staging pipeline to create converted_turnover, and then uses converted_turnover in the imputation stage. It adds "auxiliary_imputation" to the config, to refer to the auxiliary variable (converted_turnover) that is being used in imputation.
> Update stage_dataframe to calculate monthly actual pounds and use this in imputation

- Jenkinsfile
- setup.cfg
Changed the url from "http" to "https". Also changed the build branch for testing purposes; this needs to be undone.
- [V] Bug fix
> Fix Jenkins

- mbs_results/outlier_detection/detect_outlier.py
- mbs_results/utilities/constrains.py
- tests/data/utilities/constrains/no_further_processing_required.csv
- tests/data/utilities/constrains/no_further_processing_required_expected.csv
- tests/data/utilities/constrains/outlier_identified_example_1.csv
- tests/data/utilities/constrains/outlier_identified_example_1_expected.csv
- tests/data/utilities/constrains/outlier_identified_example_2.csv
- tests/data/utilities/constrains/outlier_identified_example_2_expected.csv
- tests/data/utilities/constrains/outlier_identified_example_derived_q42.csv
- tests/data/utilities/constrains/outlier_identified_example_derived_q42_expected.csv
- tests/data/utilities/constrains/outlier_identified_example_derived_q46.csv
- tests/data/utilities/constrains/outlier_identified_example_derived_q46_expected.csv
- tests/data/utilities/constrains/outlier_identified_example_q46_q47.csv
- tests/data/utilities/constrains/outlier_identified_example_q46_q47_expected.csv
- tests/utilities/test_constrains.py
This PR does  processing for post winsorisation outlier weights and winsorised values so they will match their respective components.
> 808 post wins processing

- mbs_results/outputs/turnover_analysis.py
- tests/data/outputs/turnover_analysis/turnover_analysis_output.csv
> Removing froempment and error_res columns from the TAT code

- mbs_results/outlier_detection/detect_outlier.py
Fix bug
Fix bug when calling update winsorised weight
> forgot to update this variable when calling function

- setup.cfg
> Bump version to 0.1.4

- mbs_results/outputs/period_zero_se_wrapper.py
- mbs_results/outputs/produce_additional_outputs.py
- mbs_results/outputs/selective_editing_outputs.py
> Undo test file change from merge

- mbs_results/configs/README.md
- mbs_results/configs/config_user.json
- mbs_results/imputation/impute.py
- mbs_results/imputation/ratio_of_means.py
- mbs_results/staging/back_data.py
- tests/data/staging/back_data/test_config.json
- tests/imputation/test_ratio_of_means.py
- tests/imputation/test_ratio_of_means_back_data.py
- tests/staging/test_back_data.py
- tests/test_main.py
> Rename revision_period to revision_window

- mbs_results/staging/stage_dataframe.py
- mbs_results/utilities/validation_checks.py
- tests/utilities/test_validation_checks.py
> 819 update se validation

- mbs_results/staging/stage_dataframe.py
- tests/data/staging/missing_construction_link/missing_construction_link_inputs.csv
- tests/data/staging/missing_construction_link/missing_construction_link_outputs.csv
- tests/staging/test_check_construction_links.py
- Create validation function for q49 con link
- Updated new construction link calculation to handle zero matched pairs
> Created SE construction link check for q49

- mbs_results/outputs/get_additional_outputs.py
- mbs_results/outputs/produce_additional_outputs.py
- tests/outputs/test_get_additional_outputs.py
I have added a "selective_editing" parameter to get_additional_outputs() to filter the functions to run so that it won't return a value error.
> Fix broken Dev config setup

- mbs_results/staging/stage_dataframe.py
> Ensuring formtype is checked as int

- setup.cfg
Update setup.cfg to bump version
> Bump version - 0.1.6

- mbs_results/configs/config_dev.json
- mbs_results/final_outputs.py
- mbs_results/outputs/selective_editing_outputs.py
- setup.cfg
Changes to SE output methods, created entry point
> Minor Changes to SE output code

- mbs_results/imputation/impute.py
- mbs_results/main.py
- mbs_results/staging/back_data.py
- mbs_results/staging/data_cleaning.py
- mbs_results/staging/stage_dataframe.py
Impute wrapper MBS
Modified the impute wrapper so the data cleaning/reading in functions are called in the stage_dataframe wrapper instead, since these aren't technically part of imputation.
> 671 impute wrapper mbs

- setup.cfg
Update version in setup.cfg to 0.1.8
bump version
> Update version in setup.cfg to 0.1.8

- docs/contributor_guide/CONTRIBUTING.md
- docs/user_guide/naming_conventions.md
Updated the Jenkins information in Contributing and some terms in naming conventions.
> Documentation update

- mbs_results/configs/config_user.json
Remove snapshot_alternate_path from config
Continuation of [this PR](https://github.com/ONSdigital/construction-survey-results/pull/22) as I forgot to make this change as part of the same PR, and it felt like more work re-opening that PR than just creating a new one. Just need to remove the snapshot_alternate_path parameter from the config as this is no longer needed.
> Remove snapshot_alternate_path from config

- mbs_results/configs/config_dev.json
- mbs_results/staging/data_cleaning.py
- mbs_results/staging/stage_dataframe.py
- tests/data/staging/data_cleaning/test_convert_nil_values_input.csv
- tests/data/staging/data_cleaning/test_convert_nil_values_input_warning.csv
- tests/data/staging/data_cleaning/test_convert_nil_values_output.csv
- tests/staging/test_data_cleaning.py
*Add function with warnings and logging
*Add test basic scenarios
*Add nil values and status column to dev config
*Call function to staging wrapper
This PR features a function for staging wrapper which converts values for nil markers to 0, can be configured from args in config dev. It logs column info for debugging and raises warning if tries to modify a non zero nil value
> 1030 Set NIL markers to 0 in staging

- mbs_results/configs/README.md
- mbs_results/configs/config_dev.json
- mbs_results/configs/config_user.json
- mbs_results/main.py
- mbs_results/outputs/csdb_output.py
- mbs_results/outputs/get_additional_outputs.py
- mbs_results/outputs/ocea_srs_outputs.py
- mbs_results/outputs/produce_additional_outputs.py
- mbs_results/outputs/qa_output.py
- tests/outputs/test_csdb_output.py
- tests/outputs/test_get_additional_outputs.py
- tests/outputs/test_produce_srs_ocea_outputs.py
- tests/outputs/test_qa_outputs.py
- tests/test_main.py
> Refactor additional outputs

- setup.cfg
> Upgrade setup to 0.1.10

- mbs_results/utilities/csw_to_spp_converter.py
> Update csw_to_spp_converter to account for form sent out response types

- setup.cfg
> increase version to create release

- mbs_results/staging/stage_dataframe.py
- mbs_results/utilities/validation_checks.py
- tests/utilities/test_validation_checks.py
> Asap 726 mc validation check

- mbs_results/outlier_detection/detect_outlier.py
> Update winsorisation to use auxiliary not auxiliary converted

- mbs_results/outputs/produce_additional_outputs.py
- mbs_results/outputs/scottish_welsh_gov_outputs.py
Update get_additional_outputs_df
Recent change to get_additional_outputs_df caused some issues with the cons pipeline - by appending the filtered questions, it was causing NAs which were changing some datatypes from ints to floats. This corrects that, and adds in append_filtered_questions only where it's needed (in the devolved outputs).
I also changed get_additional_outputs_df so it converts the cell_number to a numeric type. This may not be necessary for MBS, but it's affecting multiple functions in Cons (they're still getting converted to numeric throughout the pipeline) so I thought it makes more sense to convert it here rather than converting it across multiple functions (and it makes get_additional_outputs_df less redundant!) - but I'm open to hearing other options if people …
> Update get_additional_outputs df to remove append_filtered_questions

- mbs_results/configs/config_dev.json
- mbs_results/outputs/produce_additional_outputs.py
- mbs_results/utilities/pounds_thousands.py
- tests/data/outputs/additional_output_pounds_thousands/pounds_thousands_expected_mbs.csv
- tests/data/outputs/additional_output_pounds_thousands/pounds_thousands_input_mbs.csv
- tests/outputs/test_pounds_thousands.py
Add pounds-thousands conversion utility and integrate into additional outputs
1. New module: mbs_results.utilities.pounds_thousands.create_pounds_thousands_column
- Creates `adjustedresponse_pounds_thousands` by dividing selected `adjustedresponse` values by `1000`
- List-driven: only converts question numbers present in config_dev
2. Integration: call `create_pounds_thousands_column` inside `get_additional_outputs_df` (before constructing `additional_outputs_df`)
- Uses config keys (pounds_thousands_questions, question_no / questioncode, target, pound_thousand_col)
3. Tests: added unit test (`tests/outputs/test_pounds_thousands.py`) and test fixtures / data to verify:
- Only listed questions are converted
- Non-numeric free-text questions (Q146) are not converted 
- MBS-specific …
> add pounds thousands column module

- mbs_results/estimation/estimate.py
> adding cons region fix

- setup.cfg
> Version bump 0.1.16

- MANIFEST.in
- mbs_results/README.md
- mbs_results/utilities/copy_script_and_config.py
> Update Copy Script to include README file and Update the README file

- setup.cfg
The MBS entry point was the same as Cons for "additional_outputs" which was causing a clash when both packages are installed.
> Update additional outputs entry point to be specific to MBS

- setup.cfg
> bump version -> 0.1.18
